services:
  backend-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-container-test
    ports:
      - 8000:3003
    env_file:
      - .env.test

    depends_on:
      - db-test
    restart: unless-stopped
    networks:
      - groceries-app-test
  db-test:
    image: postgres:17
    container_name: postgres-container-test
    env_file:
      - .env.test
    ports:
      - 5434:5432
    volumes:
      - postgres-data-test:/var/lib/postgresql/data
    restart: always
    networks:
      - groceries-app-test

networks:
  groceries-app-test:
volumes:
  postgres-data-test:
