services:
  backend:
    image: ghcr.io/horttanainensami/groceries-backend:latest
    container_name: groceries-backend-container
    ports:
      - 8000:3003
    env_file:
      - .env.dev
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - groceries-app
  db:
    image: postgres:17
    container_name: groceries-postgres-container
    env_file:
      - .env.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - groceries-app

networks:
  groceries-app:
volumes:
  postgres-data:
